# Generated by Django 5.2.5 on 2025-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuriosidadesDeLasObras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curiosidad de la Obra',
                'verbose_name_plural': 'Curiosidades de las Obras',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
