# Generated by Django 5.2.5 on 2025-11-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Artista')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País de Origen')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='obraarte',
            name='artista',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Artista (texto)'),
        ),
        migrations.AlterField(
            model_name='obraarte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Imagen de la Obra'),
        ),
        migrations.AddField(
            model_name='obraarte',
            name='artista_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.artista', verbose_name='Artista (relación)'),
        ),
        migrations.AddField(
            model_name='obraarte',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.categoria', verbose_name='Categoría'),
        ),
    ]
