# Generated by Django 5.2.7 on 2025-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
